name: friday-admin-dashboard
databases:
- engine: PG
  name: db
  version: "15"
  production: false
services:
- name: frontend
  dockerfile_path: frontend/Dockerfile
  source_dir: frontend
  github:
    branch: main
    deploy_on_push: true
    repo: judith-friday/friday-admin-dashboard
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  envs:
  - key: NEXT_PUBLIC_API_URL
    scope: RUN_TIME
    value: ${backend.PRIVATE_URL}

- name: backend
  dockerfile_path: backend/Dockerfile
  source_dir: backend
  github:
    branch: main
    deploy_on_push: true
    repo: judith-friday/friday-admin-dashboard
  http_port: 3001
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /api
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}